# This is a global configuration file that applies to all Config-Server configurations.

#Eureka Config for all services
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#Zipkin config
management:
  tracing:
    sampling:
      probability: 1.0
  #Actuator config
  endpoints:
    web:
      exposure:
        include: "*"

  spring.zipkin.baseUrl: <http://localhost:9411>
