# This is a global configuration file that applies to all Config-Server configurations.

#Eureka Config for all services
eureka.client:
  service-url.defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"   # List specific endpoints to expose (use '*' for all)